- defaults:
    link:
      relink: true

- clean: ['~']

- link:
- link:
    ~/.zshrc: .zshrc
    ~/.zshrc: .zshrc

- create:
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
